spring:
  application:
    name: Aides
  datasource:
    username: root
    password: "011026"
    url: jdbc:mysql://localhost:3306/aides?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  data:
    redis:
      host: localhost
      port: 6379
      password: "011026"
  mail:
    host: smtp.qq.com
    username: "northboat@qq.com"
    password: "cckrfidlqckzeabb"
    default-encoding: UTF-8


#整合mybatis
mybatis:
  type-aliases-package: com.northboat.shadow.pojo
  # classpath 指 resources 目录
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8080